HW_7_MusicPortal/HW_7_MusicPortal/Models/AddTrackViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using MusicPortal.BLL.DTO;
using System.ComponentModel.DataAnnotations;

namespace HW_7_MusicPortal.Models
{
    public class AddTrackViewModel
    {
        [Required(ErrorMessage = "(Choise Genre)")]
        public int? GenreId { get; set; }
        public SelectList? Genre { get; set; }
        [Required(ErrorMessage = "(Choise Category)")]
        public int? CategoryId { get; set; }
        public SelectList? Category { get; set; }
        [Required(ErrorMessage = "(Choise Performer)")]
        public int? PerformerId { get; set; }
        public SelectList? Performer { get; set; }
        [Required(ErrorMessage = "(Choise Album)")]
        public int? AlbumId { get; set; }
        public SelectList? Album { get; set; }
    }
}

HW_7_MusicPortal/HW_7_MusicPortal/Models/EditGenreViewModel.cs
using MusicPortal.BLL.DTO;


namespace HW_7_MusicPortal.Models
{
    public class EditGenreViewModel
    {

        public string? GenreTitel { get; set; }
        public int GenreId {  get; set; }
        public PageViewModel? PageViewModelGenre { get; set; }
        public IEnumerable<GenreDTO>? Genres { get; set; }
        public EditGenreViewModel(){}
        public EditGenreViewModel(PageViewModel viewModel,IEnumerable<GenreDTO> genres ) { 
        
            PageViewModelGenre= viewModel;
            Genres= genres;
        
        }
    }
}

HW_7_MusicPortal/HW_7_MusicPortal/Models/EditTrackViewModel.cs
using MusicPortal.BLL.DTO;

namespace HW_7_MusicPortal.Models
{
    public class EditTrackViewModel
    {
        public string? TrackTitel { get; set; }
        public int TrackId { get; set; }
        public IEnumerable<TrackDTO>? Tracks { get; set; }
        public PageViewModel? Page { get; set; }
        public EditTrackViewModel() { }
        public EditTrackViewModel (IEnumerable<TrackDTO>? tracks, PageViewModel? page)
        {
            Tracks = tracks;
            Page = page;
        }
    }
}

HW_7_MusicPortal/HW_7_MusicPortal/Models/FormModels/AddTrackViewModel.cs
using HW_7_MusicPortal.Filters;
using Microsoft.AspNetCore.Mvc.Rendering;
using Resources;
using System.ComponentModel.DataAnnotations;

namespace HW_7_MusicPortal.Models.FormModels
{
    [Culture]
    public class AddTrackViewModel
    {
        [Required(ErrorMessageResourceType=typeof(Resource),ErrorMessageResourceName = "ChoiseGenre")]
        
        public int? GenreId { get; set; }
        public SelectList? Genre { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resource), ErrorMessageResourceName = "ChoiseCategoty")]

        public int? CategoryId { get; set; }
        public SelectList? Category { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resource), ErrorMessageResourceName = "ChoisePerformer")]
        public int? PerformerId { get; set; }
        public SelectList? Performer { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resource), ErrorMessageResourceName = "ChoiseAlbum")]
        public int? AlbumId { get; set; }
        public SelectList? Album { get; set; }
    }
}

HW_7_MusicPortal/HW_7_MusicPortal/Controllers/Administrator/MusicController.cs
using HW_7_MusicPortal.Models;
using Microsoft.AspNetCore.Mvc;
using MusicPortal.BLL.Interfaces;
using MusicPortal.BLL.DTO;
using Microsoft.AspNetCore.Mvc.Rendering;
using MusicPortal.DAL.Entities;
using HW_7_MusicPortal.Models.FormModels;
using Microsoft.AspNetCore.Mvc.RazorPages;
using HW_7_MusicPortal.Filters;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace HW_7_MusicPortal.Controllers.Administrator
{
    [Culture]
    public class MusicController : Controller
    {

        private readonly IInformationService? _InformationService;
        private readonly IAdminService? _AdminService;
        private IWebHostEnvironment? _environment;
        private readonly ILogger<MusicController>? _logger;
        private const int pageSize = 24;
        private const int pageSizeTrack = 24;
        public MusicController(
            IInformationService informationService,
            IAdminService adminService,
            IWebHostEnvironment path,
            ILogger<MusicController> logger) { 
        
            _InformationService = informationService;
            _AdminService = adminService;
            _environment = path;
            _logger = logger;
        
        
        }
        public async Task<IActionResult> EditGenre(int page=1)
        {
            var Genres = await _InformationService.GetAllGenreAsync();
            var count = Genres.Count();
            var itemsG = Genres.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            PageViewModel pageViewModelG = new PageViewModel(count, page, pageSize);
            EditGenreViewModel infoGenre = new EditGenreViewModel(pageViewModelG, itemsG);

            return View(infoGenre);
        }
        public async Task<IActionResult> EditTrack(int editPageTrack=1)
        {
            var tracks = await _InformationService.GetAllTrackAsync();
            var count = tracks.Count();
            var items = tracks.Skip((editPageTrack - 1) * pageSizeTrack).Take(pageSizeTrack).ToList();
            PageViewModel pageViewModelEditT = new PageViewModel(count, editPageTrack, pageSizeTrack);
            EditTrackViewModel ifoTrack = new EditTrackViewModel(items, pageViewModelEditT);
            return View(ifoTrack);
        }
        public async Task<IActionResult> DeleteGenre(int id)// only Db
        {
            await _AdminService.DeleteGenreAsync(id);
            return RedirectToAction("EditGenre");
        }/** To-do Delete Local **/
        public async Task<IActionResult> DeleteTrack(int id)// only Db
        {
            await _AdminService.DeleteTrackAsync(id);
            return RedirectToAction("EditTrack");
        }/** To-do Delete Local **/

        public async Task<IActionResult> ConFirm(EditGenreViewModel genreUpdate=null!)
        {
            //_logger.LogInformation(${ })

            var oldPath = await _InformationService.GetGenreAsync(genreUpdate.GenreId);
            string targetUpdate = _environment.WebRootPath + $"\\Music\\{oldPath.Title}";
            DirectoryInfo di = new DirectoryInfo(targetUpdate);
            await Task.Run(() => di.MoveTo($"{_environment.WebRootPath}\\Music\\{genreUpdate.GenreTitel}"));
            await _AdminService.UpdateGenreAsync(new GenreDTO { Title=genreUpdate.GenreTitel,Id=genreUpdate.GenreId});
            await _AdminService.UpdateSrcExcute($"/Music/{oldPath.Title}", $"/Music/{genreUpdate.GenreTitel}");
            return RedirectToAction("EditGenre");
        }

        public async Task<IActionResult> AddGenre()
        {
            GenreViewModel ingomminGenre=new GenreViewModel();
            ingomminGenre.CategoryL = new SelectList(await _InformationService.GetAllCategoryAsync(), nameof(Category.Title), nameof(Category.Title));
            ingomminGenre.PerformerL = new SelectList(await _InformationService.GetAllPerformerAsync(), nameof(Performer.Name), nameof(Performer.Name));
            ingomminGenre.GenriL = new SelectList(await _InformationService.GetAllGenreAsync(), nameof(Genre.Title), nameof(Genre.Title));
            return View(ingomminGenre);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddGenre(GenreViewModel ingomminGenre)
        {

            if (!string.IsNullOrEmpty(ingomminGenre.Genre))
            {
                if (Directory.Exists(_environment.WebRootPath + $"\\Music\\{ingomminGenre.Genre}"))
                {
                    ModelState.AddModelError("", Resources.Resource.GenreHasAlready);

                }
                else
                {
                    if (ModelState.IsValid)
                    {
                        Directory.CreateDirectory(_environment.WebRootPath + $"\\Music\\{ingomminGenre.Genre}");
                        await _AdminService?.CreateGenreAsync(new CreateGenreDTO { Genre = ingomminGenre.Genre });
                        return RedirectToAction("AddGenre");
                    }
                  


                }

            }
            else if (!string.IsNullOrEmpty(ingomminGenre.OptionGenre) && !string.IsNullOrEmpty(ingomminGenre.Category))
            {

                if (Directory.Exists(_environment.WebRootPath + $"\\Music\\{ingomminGenre.OptionGenre}\\{ingomminGenre.Category}"))
                {
                    ModelState.AddModelError("", Resources.Resource.CategoryHasAlready);
                }
                else
                {
                    if (ModelState.IsValid)
                    {
                        Directory.CreateDirectory(_environment.WebRootPath + $"\\Music\\{ingomminGenre.OptionGenre}\\{ingomminGenre.Category}");
                        await _AdminService.CreateCategoryAsync(new CreateGenreDTO { Category = ingomminGenre.Category });
                    }
                }
            }
            else if (!string.IsNullOrEmpty(ingomminGenre.OptionGenre) &&
                !string.IsNullOrEmpty(ingomminGenre.OptionCategory) && !string.IsNullOrEmpty(ingomminGenre.Performer))
            {

                if (Directory.Exists(_environment.WebRootPath + $"\\Music\\{ingomminGenre.OptionGenre}\\{ingomminGenre.OptionCategory}\\{ingomminGenre.Performer}"))
                {
                    ModelState.AddModelError("", Resources.Resource.PerformerHasAlready);
                }
                else
                {
                    if (ModelState.IsValid)
                    {
                        Directory.CreateDirectory(_environment.WebRootPath + $"\\Music\\{ingomminGenre.OptionGenre}\\{ingomminGenre.OptionCategory}\\{ingomminGenre.Performer}");
                        await _AdminService.CreatePerformerAsync(new CreateGenreDTO { Performer = ingomminGenre.Performer });
                    }
                }
            }
            else if (!string.IsNullOrEmpty(ingomminGenre.OptionGenre) &&
                !string.IsNullOrEmpty(ingomminGenre.OptionCategory) &&
                !string.IsNullOrEmpty(ingomminGenre.OptionPerformer) &&
                !string.IsNullOrEmpty(ingomminGenre.Album))
            {

                if (Directory.Exists(_environment.WebRootPath + $"\\Music\\{ingomminGenre.OptionGenre}\\{ingomminGenre.OptionCategory}\\{ingomminGenre.OptionPerformer}\\{ingomminGenre.Album}"))
                {
                    ModelState.AddModelError("",Resources.Resource.AlbumHasAlready);
                }
                else
                {
                    if (ModelState.IsValid)
                    {
                        Directory.CreateDirectory(_environment.WebRootPath + $"\\Music\\{ingomminGenre.OptionGenre}\\{ingomminGenre.OptionCategory}\\{ingomminGenre.OptionPerformer}\\{ingomminGenre.Album}");
                        await _AdminService.CreateAlbumAsync(new CreateGenreDTO { Album = ingomminGenre.Album });
                        return RedirectToAction("AddGenre");
                    }
                }
            }
            else
            {
                
                if (!string.IsNullOrEmpty(ingomminGenre.Category)&&string.IsNullOrEmpty(ingomminGenre.OptionGenre))
                {

                    ModelState.AddModelError("", Resources.Resource.CategoryOnlyInGnere);

                }
                if (!string.IsNullOrEmpty(ingomminGenre.Performer) && string.IsNullOrEmpty(ingomminGenre.OptionCategory))
                {

                    ModelState.AddModelError("", Resources.Resource.PerformerOnlyInCategory);

                }

                if (!string.IsNullOrEmpty(ingomminGenre.Album) && 
                    string.IsNullOrEmpty(ingomminGenre.OptionPerformer)|| 
                    string.IsNullOrEmpty(ingomminGenre.OptionCategory)||
                    string.IsNullOrEmpty(ingomminGenre.OptionGenre))
                {

                    ModelState.AddModelError("", Resources.Resource.AlbumOnly);
         
                    
                   

                }
               


            }

            //To--do Check path
            ingomminGenre.CategoryL = new SelectList(await _InformationService.GetAllCategoryAsync(), nameof(Category.Title), nameof(Category.Title));
            ingomminGenre.PerformerL = new SelectList(await _InformationService.GetAllPerformerAsync(), nameof(Performer.Name), nameof(Performer.Name));
            ingomminGenre.GenriL = new SelectList(await _InformationService.GetAllGenreAsync(), nameof(Genre.Title), nameof(Genre.Title));
            return View(ingomminGenre);
          
        }

        public async Task<IActionResult> AddTrack()
        {

            AddTrackViewModel vm = new AddTrackViewModel();
            vm.Genre = new SelectList(await _InformationService.GetAllGenreAsync(), nameof(Genre.Id), nameof(Genre.Title));
            vm.Category = new SelectList(await _InformationService.GetAllCategoryAsync(), nameof(Category.Id), nameof(Category.Title));

HW_7_MusicPortal/HW_7_MusicPortal/Views/Music/AddGenre.cshtml
@model GenreViewModel


@{
    Layout = "_AdminLayOut";
}
<div class="music-management">

    <form class="genre-form boxShadow borderR font-setting-form" asp-action="AddGenre">

        <span class="info">
            <div asp-validation-summary="ModelOnly" class="info text-danger"></div>
        </span>

        <div class="field-group">
            <input placeholder="@Resource.Genre" class="info borderR" asp-for="Genre" />
            <span asp-validation-for="Genre" class="text-danger"></span>

        </div>

        <select class="info borderR field-group" asp-for="OptionGenre" asp-items="Model.GenriL">
        <option value="" selected="selected" >@Resource.ChoiseGenre</option>
            
        </select>
        <div class="field-group">
            <input placeholder="@Resource.Category" class="info borderR" asp-for="Category" />
            <span asp-validation-for="Category" class="text-danger"></span>
        </div>

        <select class="info borderR field-group" asp-for="OptionCategory" asp-items="Model.CategoryL">
            <option value="" selected="selected">@Resource.ChoiseCategoty</option>
            
        </select>
        <div class="field-group">
            <input placeholder="@Resource.Performer" class="info borderR" asp-for="Performer" />
            <span asp-validation-for="Performer" class="text-danger"></span>
        </div>

        
        <select class="info borderR field-group" asp-for="OptionPerformer" asp-items="Model.PerformerL">
            <option value="" selected="selected">@Resource.ChoisePerformer</option>
        </select>

        <div class="field-group">
            <input placeholder="@Resource.Album" class="info borderR" asp-for="Album" />
            <span asp-validation-for="Album" class="text-danger"></span>
        </div>

        <div class="field-group">
            <input class="info borderR back-color-button-Green" type="submit" value="@Resource.Confirm" />
        </div>
        <span></span>
    </form>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

HW_7_MusicPortal/HW_7_MusicPortal/Views/Music/AddTrack.cshtml
@model AddTrackViewModel
@{
    Layout = "_AdminLayOut";
}
<div class=" music-management">
    
    <form asp-action ="AddTrack" method="post" enctype="multipart/form-data" class="borderr form-Track font-setting-form">

        <div asp-validation-summary="ModelOnly" class="info text-danger"></div>
        <div class="field-group elemet-setting">
            <select  asp-for="GenreId" asp-items="Model.Genre">
                <option  value="" selected="selected">@Resource.ChoiseGenre</option>
            </select>
            <span asp-validation-for="GenreId" ></span>
        </div>

        <div class="field-group elemet-setting">
            <select asp-for="CategoryId" asp-items="Model.Category">
                <option value="" selected="selected">@Resource.ChoiseCategoty</option>
            </select>
            <span asp-validation-for="CategoryId"></span>
        </div>
       

        <div class="field-group elemet-setting">
            <select asp-for="PerformerId" asp-items="Model.Performer">
                <option value="" selected="selected">@Resource.ChoisePerformer</option>
            </select>
            <span asp-validation-for="PerformerId"></span>
        </div>
        

        <div class="field-group elemet-setting">
            <select  asp-for="AlbumId" asp-items="Model.Album">
                <option value="" selected="selected">@Resource.ChoiseAlbum</option>
            </select>
            <span asp-validation-for="AlbumId"></span>

        </div>
        

        <label for="file-upload" class="file-button elemet-setting">
          @Resource.UploadComposition
        </label>
        <input id="file-upload" type="file" name="uploadFile" />

         <input class="button-castom-form back-color-button-Green" type="submit" value="@Resource.Confirm" />
    </form>


</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

HW_7_MusicPortal/HW_7_MusicPortal/Views/Music/AditGenre.cshtml
@model EditGenreViewModel

@{
    Layout = "_AdminLayOut";
}


<div class="contener-item">
    <div class="eddit-genre-contener size-contener">

        @foreach (var item in Model.Genres)
        {
            <form asp-action="ConFirm" class="card-genre-edit">
                <span class="font-settings-edit-genre">Genre</span>
                <div>
                    <input asp-for="GenreId" hidden value="@item.Id" />
                    <input asp-for="GenreTitel" class="textInput custom-input" value="@item.Title" readonly /><br />
                </div>
                <div>
                    <input class="back-color-button-Green font-color-general button-castom" type="submit" value="Confirm" />
                    <a asp-action="DeleteGenre" asp-controller="Music" asp-route-id="@item.Id"><input type="button" class="back-color-button-Red button-castom" value="Delete" /></a>

                </div>

            </form>

        }
    </div>

    <span><paginations page-action="AditGenre"  pagination-track="Model.PageViewModelGenre" parametr="page"></paginations> </span>

</div>

HW_7_MusicPortal/HW_7_MusicPortal/Views/Music/EditGenre.cshtml
@model EditGenreViewModel

@{
    Layout = "_AdminLayOut";
}


<div class="contener-item">
    <div class="eddit-genre-contener size-contener">

        @foreach (var item in Model.Genres)
        {
            <form asp-action="ConFirm" class="card-genre-edit">
                <span class="font-settings-edit-genre">@Resource.Genre</span>
                <div>
                    <input asp-for="GenreId" hidden value="@item.Id" />
                    <input asp-for="GenreTitel" class="textInput custom-input" value="@item.Title" readonly /><br />
                </div>
                <div>
                    <input class="back-color-button-Green font-color-general button-castom" type="submit" value="@Resource.Confirm" />
                    <a asp-action="DeleteGenre" asp-controller="Music" asp-route-id="@item.Id"><input type="button" class="back-color-button-Red button-castom" value="@Resource.Delete" /></a>

                </div>

            </form>

        }
    </div>

    <span><paginations page-action="EditGenre" pagination-track="Model.PageViewModelGenre" parametr="page"></paginations> </span>

</div>

HW_7_MusicPortal/HW_7_MusicPortal/Views/Music/EditTrack.cshtml
@model EditTrackViewModel

@{
    Layout = "_AdminLayOut";
}
<div class="contener-item">
    <div class="eddit-genre-contener size-contener">

        @foreach (var item in Model.Tracks)
        {
            <form asp-action="ConFirmTrack" class="card-genre-edit">
                <span class="font-settings-edit-genre">@item.Performer</span>
                <div>
                    <input asp-for="TrackId" hidden value="@item.Id" />
                    <input asp-for="TrackTitel" class="textInput custom-input" value="@item.Title" readonly /><br />
                </div>
                <div>
                    <input class="back-color-button-Green font-color-general button-castom" type="submit" value="@Resource.Confirm" />
                    <a asp-action="DeleteTrack" asp-controller="Music" asp-route-id="@item.Id"><input type="button" class="back-color-button-Red button-castom" value="@Resource.Delete" /></a>

                </div>

            </form>

        }
    </div>
    <span> <paginations page-action="EditTrack" pagination-track="Model.Page" parametr="editPageTrack"></paginations></span>

</div>