HW_ 6_GuestBook_IRepository/HW_ 6_GuestBook_IRepository/Controllers/MessageController.cs
using HW__6_GuestBook_IRepository.Data.Repository;
using HW__6_GuestBook_IRepository.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text.RegularExpressions;

namespace HW__6_GuestBook_IRepository.Controllers
{
    public class MessageController : Controller
    {
        private string pattern= @"[?!,.a-z,A-Zа-я,А-ЯёЁ,0-9]{1,15}";
        private Regex optionRegex;
        private readonly ILogger<HomeController>? _logger;
        private readonly IRepository? _repository;
        public MessageController(ILogger<HomeController> logger, IRepository repository) { 
        
            _logger = logger;
            _repository = repository;
            optionRegex = new Regex(pattern,RegexOptions.IgnoreCase);

        }
        public IActionResult MessageSend()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> MessageSend(ViewModelPublish incommingMessage)
        {

            if (ModelState.IsValid)
            {
                await _repository.CreateMessageAsync(new Message { UserMessage = incommingMessage.Message, Theme = incommingMessage.Theme }, HttpContext.Session.GetString("login"));
                await _repository.SaveChangeAsync();
                string response = "All done";
                return Json(response);

            }
            return Problem("something wrong");
        }
    }
}

HW_ 6_GuestBook_IRepository/HW_ 6_GuestBook_IRepository/Controllers/RegistrationController.cs
using HW__6_GuestBook_IRepository.Data.Repository;
using HW__6_GuestBook_IRepository.Models;
using HW__6_GuestBook_IRepository.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace HW__6_GuestBook_IRepository.Controllers
{
    public class RegistrationController : Controller
    {


        private readonly ILogger<RegistrationController>? _logger;
        private readonly Encryption? _encryption;
        public readonly IRepository? _repository;
        public RegistrationController(ILogger<RegistrationController> logger,IRepository repository, Encryption encryption) { 
        
            _repository = repository;
            _encryption = encryption;
            _logger = logger;
        }
        public IActionResult UserRegistration()
        {
            return View();
        }

        [AcceptVerbs("Get", "Post")]
        public async Task <IActionResult> CheckLogin(string login)
        {
            return Json(await _repository.IsLoginAsync(login));

        }

        [AcceptVerbs("Get", "Post")]
        public async Task<IActionResult> CheckNickName(string nickName)
        {
            return Json(await _repository.IsNickNameAsync(nickName));

        }



        [HttpPost]
        public IActionResult UserRegistration(ViewModelRegistration incomminUser)
        {
          
            if (incomminUser.Login.ToLower() == "login" || incomminUser.NickName.ToLower() == "nickName"
                || incomminUser.Password.ToLower() == "password")
            {

                ModelState.AddModelError("", "The data is not correct");
            }

            if (ModelState.IsValid)
            {

                _encryption.Pass = incomminUser.Password;
                _encryption.HashPass();
                User user = new User();
                user.Password = _encryption.PassDb;
                user.Salt = _encryption.SaltDb;
                user.Login = incomminUser.Login;
                user.NickName = incomminUser.NickName;

                _repository.CreateUserAsync(user);
                _repository.SaveChangeAsync();


                return Json(new { response = "Alldone" });


            }
            return Problem("Something wrong");
        }


      
    }
}

HW_ 6_GuestBook_IRepository/HW_ 6_GuestBook_IRepository/Views/Shared/_GuestBook.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/GuestBookMain.css" asp-append-version="true" />
   
</head>
<body>
    <main>
        <aside class="sideBar">
            <div id="menu" class="menu">
                <span id="user" class="logginUser">Вы вошли как  @Context.Session.GetString("login")</span>

                <h2><a asp-action="Loggin" asp-controller="Loggin" class="button">Войти</a></h2>
                <h2><a asp-action="Logout" asp-controller="Loggin" class="button">Выйти</a></h2>
                <h2><a asp-action="UserRegistration" asp-controller="Registration" class="button">Регистрация</a></h2>
                <h2><a asp-action="MessageSend" asp-controller="Message" class="button">Написать сообщение</a></h2>
                <h2><a asp-action="Index" id="testAjax" asp-controller="Home" class="button">Дом</a></h2>
            </div>
        </aside>
        <section>
            <div class="messageContanier">
                @RenderBody()
               
            </div>
           
            
        </section>
       
    </main>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script type="module" src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HW_ 6_GuestBook_IRepository/HW_ 6_GuestBook_IRepository/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] -GuestBook</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HW__6_GuestBook_IRepository.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HW__6_GuestBook_IRepository</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - HW__6_GuestBook_IRepository - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script  src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>