HW_4_Top_10_CRUD/HW_4_Top_10_CRUD/Controllers/EditController.cs
using HW_4_Top_10_CRUD.Data;
using HW_4_Top_10_CRUD.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HW_4_Top_10_CRUD.Controllers
{
    public class EditController : Controller
    {

        private readonly TenMoviesContext? _context;
        private IWebHostEnvironment? _environment;
        private string? pathSave;
        public EditController(TenMoviesContext context, IWebHostEnvironment path)
        {
            _context = context;
            _environment = path;

        }
        public async Task<IActionResult>  EditMovie(int id)
        {

            AllInfoModelView modelView = new AllInfoModelView();
            var src = await _context.Movies.Where(e => e.Id == id).FirstAsync();

            modelView.Id = src.Id;
            modelView.Title = src.Title;
            modelView.Description = src.Description;
            modelView.Actors = src.Actors;
            modelView.Director = src.Director;
            modelView.Genre = src.Genre;
            modelView.Language = src.Language;
            modelView.PosterUrl = src.PosterUrl;
           // modelView.Year = src.Year;
            modelView.Runtime = src.Runtime;    

            return View(modelView);
        }


        [HttpPost]
        [RequestSizeLimit(1000000)]
        [ValidateAntiForgeryToken]//Chek control sum;
        public async Task <IActionResult> UpDateMovie(
           [Bind("Id,Title,Description,Genre,PosterUrl,Runtime,Director,Actors,Language,Year")] AllInfoModelView movie, IFormFile uploadPoster)
        {


            if (uploadPoster is not null)
            {
                pathSave = "/imgSrc/posters/" + uploadPoster.FileName;

                using (var fileStream = new FileStream(_environment.WebRootPath + pathSave, FileMode.Create))
                {

                   await uploadPoster.CopyToAsync(fileStream);

                }

            }

            var target= await _context.Movies.FirstOrDefaultAsync(e=>e.Id==movie.Id);
            if(target != null)
            {

                target.Title=movie.Title;

                target.Title = movie.Title;
                target.Description = movie.Description;
                target.Actors = movie.Actors;
                target.Director = movie.Director;
                target.Genre = movie.Genre;
                target.Language = movie.Language;
                target.Runtime = movie.Runtime;
                target.Year = movie.Year;
                if (uploadPoster is not null)
                {
                    target.PosterUrl = pathSave;
                }
               await _context.SaveChangesAsync();


            }

            
            return RedirectToAction("Index","Home");
        }
    }
}

HW_4_Top_10_CRUD/HW_4_Top_10_CRUD/Controllers/HomeController.cs
using HW_4_Top_10_CRUD.Data;
using HW_4_Top_10_CRUD.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HW_4_Top_10_CRUD.Controllers
{
    public class HomeController : Controller
    {
        private TenMoviesContext? _context;
        public HomeController(TenMoviesContext contex) { 
       
            _context = contex;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _context.Movies.ToListAsync());
        }
        public async Task<IActionResult> Details(int id)
        {
            AllInfoModelView modelView = new AllInfoModelView();
           var src = await _context.Movies.Where(e => e.Id == id).FirstAsync();
           
            modelView.Title = src.Title;
            modelView.Description = src.Description;
            modelView.Actors = src.Actors;
            modelView.Director= src.Director;
            modelView.Genre= src.Genre;
            modelView.Language = src.Language;
            modelView.PosterUrl = src.PosterUrl;
            modelView.Year = src.Year;
            modelView.Runtime = src.Runtime;
            return PartialView("Details", modelView);
        }


        public async Task<IActionResult> Delete(int id)
        {
            _context.Movies.Remove(await _context.Movies.FirstOrDefaultAsync(e => e.Id == id));
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

HW_4_Top_10_CRUD/HW_4_Top_10_CRUD/ViewComponents/DetailsViewComponent.cs
using HW_4_Top_10_CRUD.Data;
using HW_4_Top_10_CRUD.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HW_4_Top_10_CRUD.ViewComponents
{
    public class DetailsViewComponent:ViewComponent
    {
        private readonly TenMoviesContext? _context;
        public DetailsViewComponent(TenMoviesContext context)
        {
            _context = context;

        }

        public async Task<IViewComponentResult> InvokeAsync(int id)
        {

            AllInfoModelView modelView = new AllInfoModelView();
             var test= await _context.Movies.Where(e=>e.Id==id).FirstOrDefaultAsync();

            modelView.Title=test.Title; 
            modelView.Description=test.Description;


            return View("Default",modelView);
        }
       

    }
}

HW_4_Top_10_CRUD/HW_4_Top_10_CRUD/Views/Home/Details.cshtml
@model AllInfoModelView

@* @model Movie *@


<div id="forCard" class="forCard">
    <div class="cardFilm borderR boxShadow">
        <div class="poster rowSpan borderLR" style="background-image:url(@Html.DisplayFor(Model=>Model.PosterUrl))">
        </div>
        <div class=" rowSpan dispalayGrid gridTempRow">
            <span class="info">
                @Html.DisplayFor(Model=>Model.Title)
            </span>
            <span class="info">
                @Html.DisplayFor(Model=>Model.Year)
            </span>
            <span class="info">
                @Html.DisplayFor(Model=>Model.Genre)
            </span>
            <span class="info">
                @Html.DisplayFor(Model => Model.Actors)
            </span>
            <span class="info">
                @Html.DisplayFor(Model => Model.Director)
            </span>
            <span class="info">
                @Html.DisplayFor(Model => Model.Language)
            </span>
            <span class="info">
                @Html.DisplayFor(Model => Model.Runtime)
            </span>

            <span class=" borderR description ">
                @Html.DisplayFor(Model=>Model.Description)
            </span>
        </div>
    </div>
</div>

HW_4_Top_10_CRUD/HW_4_Top_10_CRUD/Views/Home/Index.cshtml
@model IEnumerable<Movie>
@addTagHelper *, MyWebApp

@{
    ViewData["Title"] = "TenMovies";
    Layout = "_TenMovies";
}


@await Html.PartialAsync("Details",new AllInfoModelView());


@* @await Component.InvokeAsync("Details", 5); *@
<div id="pagination">

    <div class="cardFilmP borderR boxShadow">
        
        <div class="posterP rowSpan borderLR" style="background-image:url()">
        </div>
        <div class=" rowSpan dispalayGrid gridTempRow">

            <span class="info">
               
            </span>
            <span class="info">
               
            </span>
            <span class="info">
               
            </span>
            <span class="info borderR description ">
               
            </span>
            <span class="info ">
                
            </span>
        </div>
    </div>

    @foreach (var info in Model)
    {
        <div class="cardFilmP borderR boxShadow">
            <input hidden value="@Html.DisplayFor(modelItem => info.Id)" />
            <div class="posterP rowSpan borderLR" style="background-image:url(@Html.DisplayFor(modelItem=>info.PosterUrl)">
            </div>
            <div class=" rowSpan dispalayGrid gridTempRow">
                
                <span class="info">
                       @Html.DisplayFor(modelItem => info.Title)
                </span>
                <span class="info">
                    @Html.DisplayFor(modelItem => info.Year)
                </span>
                <span class="info">
                    @Html.DisplayFor(modelItem => info.Genre)
                </span>
               
                <span class="info">
                    <a asp-action="Delete" asp-controller="Home" asp-route-id="@info.Id">Удалить</a>
                </span>
                <span class="info">
                    <a asp-action="EditMovie" asp-controller="Edit" asp-route-id="@info.Id">Редактировать</a>
                </span>
               
                
            </div>
        </div>
    }

    <div class="cardFilmP borderR boxShadow">

        <div class="posterP rowSpan borderLR" style="background-image:url()">
        </div>
        <div class=" rowSpan dispalayGrid gridTempRow">

            <span class="info">

            </span>
            <span class="info">

            </span>
            <span class="info">

            </span>
            <span class="info borderR description ">

            </span>
            <span class="info ">

            </span>
        </div>
    </div>

</div>